### ISSUE TITLE
Complex_topology.pdb not found

### ISSUE THREAD

**Issue by velocirraptor23** [openforcefield/symposium_2024_demo#1]
Hi Jeff,

I was looking for this file in the demo but I could not find it. Any help would be highly apreciated.

Best wishes,

Cesar

**Comment by j-wags** [comment]
My mistake! I've added it, could you run `git pull` and try again?

**Comment by velocirraptor23** [comment]
Hi Jeff,

Thanks a lot for your quick response. Now it works perfectly.

BW,

CEsar

**Comment by j-wags** [comment]
Excellent. Thanks for catching my glaring mistake @velocirraptor23, and apologies for the inconvenience!
